// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9E8N2bN7B5gZJX53guNJXvHW3AzIS35g',
    appId: '1:855425405657:web:93b725ff403a03330224c8',
    messagingSenderId: '855425405657',
    projectId: 'safe-hood-5b0f8',
    authDomain: 'safe-hood-5b0f8.firebaseapp.com',
    storageBucket: 'safe-hood-5b0f8.firebasestorage.app',
    measurementId: 'G-RCH1TRDLES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXz2XQR3VufGJZWnVPfOkSl-2ttAZwfy0',
    appId: '1:855425405657:android:a1d6739412ca82280224c8',
    messagingSenderId: '855425405657',
    projectId: 'safe-hood-5b0f8',
    storageBucket: 'safe-hood-5b0f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqe81Txey5K25yYsZ9moHwTvXrvwqPMA',
    appId: '1:855425405657:ios:af69e2ac3c6672ad0224c8',
    messagingSenderId: '855425405657',
    projectId: 'safe-hood-5b0f8',
    storageBucket: 'safe-hood-5b0f8.firebasestorage.app',
    iosBundleId: 'com.example.safeHood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeqe81Txey5K25yYsZ9moHwTvXrvwqPMA',
    appId: '1:855425405657:ios:af69e2ac3c6672ad0224c8',
    messagingSenderId: '855425405657',
    projectId: 'safe-hood-5b0f8',
    storageBucket: 'safe-hood-5b0f8.firebasestorage.app',
    iosBundleId: 'com.example.safeHood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9E8N2bN7B5gZJX53guNJXvHW3AzIS35g',
    appId: '1:855425405657:web:550a25886ff5a2ee0224c8',
    messagingSenderId: '855425405657',
    projectId: 'safe-hood-5b0f8',
    authDomain: 'safe-hood-5b0f8.firebaseapp.com',
    storageBucket: 'safe-hood-5b0f8.firebasestorage.app',
    measurementId: 'G-G3TK5Q1K0D',
  );
}
